Added --root-user flag to devbox generate
jetpack-io/devbox pull request #1359
Opened 2023-08-09 21:48 UTC by mohsenari

## Summary
follow up for #1325 
This also potentially fixes an issue reported for users having permission issues with `.devbox/` directory inside devcontainer because of `root` user inside the container.

Added a `--root-user` flag to allow both single user installation and multi user installation for nix as well as setup for Dockerfile and devcontainer.json.

This allows users to choose either `devbox` as a user in the container environment (default) or `root` as a user in the container environment (passing `--root-user` flag).

## How was it tested?
`devbox generate dockerfile -f -r`
compare content of Dockerfile with 
`devbox generate dockerfile -f`

2023-08-09 22:07 UTC, mikeland73 requested changes
I'm not super familiar with dockerfile changes. Some comments on golang changes.

2023-08-09 22:07 UTC, mikeland73 commented on internal/impl/generate/devcontainer_util.go
> +}
A few issues:

* Not sure about the name (`generate.Generate` is repetitive and doesn't convey what it does).
* As currently used it does not need to be exported.
* It should not contain context. (In general context should never be saved in a struct).

Proposal:

* Name it `Options` instead.
* Remove context.
* Remove Open

Code would look like:

```golang
g := &generate.Options{...}
g.CreateDockerfile(ctx)
```

2023-08-09 22:07 UTC, mikeland73 commented on internal/impl/generate/devcontainer_util.go
>  		// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
is this comment still relevant?

2023-08-11 18:31 UTC, mohsenari commented
@mikeland73 I updated the PR based on the feedback. PTAL

2023-08-11 20:27 UTC, mikeland73 approved these changes
Looks good!

I'm less confident about the dockerfile stuff so make sure that's well tested.

2023-08-11 20:27 UTC, mikeland73 commented on internal/boxcli/generate.go
> +	generateOpts := devopt.GenerateOpts{
Hack, if you embed `devopt.GenerateOpts` to the flag struct you can pass `flags.GenerateOpts` into the functions below.

2023-08-11 22:05 UTC, merged