[update] change Error: to Warning: for failed attempt to upgrade flake
jetpack-io/devbox pull request #1773
Opened 2024-02-01 19:20 UTC by savil

## Summary

When I modified the `examples/flakes/php` to omit `ds` extension and did `devbox update`, then the output alarmed me at first. 

The Error made me think something drastic went wrong. But in this case, since its an "attempt", I think we should
make it a Warning or even an Info.

```
❯ devbox update
Info: Attempting to upgrade path:my-php-flake#php using `nix profile upgrade`
Error: Failed to upgrade path:my-php-flake#php using `nix profile upgrade`: php: package not found
Info: Attempting to upgrade path:my-php-flake#hello using `nix profile upgrade`
Error: Failed to upgrade path:my-php-flake#hello using `nix profile upgrade`: hello: package not found
Info: Already up-to-date ripgrep@latest 14.1.0
[1/2] php
[1/2] php: Success
[2/2] hello
[2/2] hello: Success
✓ Computed the Devbox environment.
Info: Removing php-with-extensions@8.1.19
Warning: Your shell environment may be out of date. Run `refresh` to update it.
Info: Running "nix flake update"
(devbox)
```

## How was it tested?

```
❯ devbox update
Info: Attempting to upgrade path:my-php-flake#php using `nix profile upgrade`
Warning: Failed to upgrade path:my-php-flake#php using `nix profile upgrade`: php: package not found
Info: Attempting to upgrade path:my-php-flake#hello using `nix profile upgrade`
Warning: Failed to upgrade path:my-php-flake#hello using `nix profile upgrade`: hello: package not found
Info: Already up-to-date ripgrep@latest 14.1.0
[1/2] php
[1/2] php: Success
[2/2] hello
[2/2] hello: Success
✓ Computed the Devbox environment.
Info: Removing php-with-extensions@8.1.19
Warning: Your shell environment may be out of date. Run `refresh` to update it.
Info: Running "nix flake update"
(devbox)
```

2024-02-01 19:20 UTC, savil commented
Current dependencies on/for this PR:
* `main`
  * **PR #1773** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1773?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/jetpack-io/devbox/1773?utm_source=stack-comment).

2024-02-01 19:21 UTC, Lagoja commented
Why does the warning show at all if you're running `devbox update`?

2024-02-01 19:32 UTC, savil commented
> Why does the warning show at all if you're running `devbox update`?

its being transparent about what specifically we're trying to update and if it worked or didn't?

2024-02-02 03:11 UTC, mikeland73 reviewed
Did we decide this can be removed? We need to ensure nix build creates the latest version of a flake (I assume it does) in which case we no longer need to upgrade flakes.

2024-02-02 03:11 UTC, mikeland73 requested changes
.

2024-02-02 18:19 UTC, savil commented
@mikeland73  lets not conflate two diff discussions. I need to investigate whether this code is still needed. That will take some time given my other commitments. In the meantime, we should fix this misleading "Error:" message.

2024-02-02 18:33 UTC, mikeland73 approved these changes

2024-02-02 18:39 UTC, merged