nixstore: search packages by attribute path
jetpack-io/devbox pull request #900
Opened 2023-04-12 21:07 UTC by gcurtis

Depends on #896.

---

This is a hack to get a rudimentary package search (by attribute path) working natively in Devbox. For example, to install Go 1.19:

```go
remoteStore, _ := Remote("https://cache.nixos.org")
remotePkg, _ := remoteStore.PackageAttrPath("go_1_19")

localStore, _ := Local("/nix/store")
localStore.Install(remotePkg)
```

The attribute path lookup relies on embedding a gzipped JSON index of all nixpkgs at commit 3fb8eedc450. This file adds 4.7 MiB to the size of the Devbox binary. Ideally this index would be downloaded as-needed instead.

2023-04-12 21:09 UTC, gcurtis commented
If anyone things the embedded file is too large, I can hold off on this and get a better implementation working by downloading it at runtime.

2023-04-13 00:29 UTC, mikeland86 commented
Not necessarily opposed to embedding, but generally prefer downloading. Is this part of a general strategy for search? or is it tangential?

2023-04-13 00:36 UTC, loreto commented
I think downloading (or API) is the way to go. But in the interest of Always Be Shipping, I think it's totally cool to embed as a first pass, and get the search feature out. 4.7 MiB feels reasonable to me, so I'd be inclined to ship this!

2023-04-13 01:09 UTC, gcurtis commented
> Not necessarily opposed to embedding, but generally prefer downloading. Is this part of a general strategy for search? or is it tangential?

It's more of a first step to get something working. I don't think this will (or should) be the final implementation.

2023-05-01 22:34 UTC, mikeland86 requested changes
Should we shelve this in favor of server side search for now?

I think this is a good idea, but would prefer lazy download to avoid the increase in size but I don't think it's a priority

2023-06-02 20:51 UTC, loreto commented
Is this PR abandoned? (should we close it in that case?)

2023-06-27 02:17 UTC, closed without merging